### ISSUE TITLE
Spot.System.GetExchangeInfoAsync()  Raise a strange Exception

### ISSUE THREAD

**Issue by heavymanto** [JKorf/Binance.Net#1009]
**Describe the bug**
From yesterday night Spot.System.GetExchangeInfoAsync()  Raise a strange Exception. Is a Binance Error? 
A use Binance.Net, Version=7.2.6.0. I have test an update to last version but my code not compile because miss IExchangeClient. Have you change reference? Can i acess to this interface?

Thank,
m.F.

**To Reproduce**
![image](https://user-images.githubusercontent.com/6449169/155700184-cc9ae62d-d76f-433e-b7da-5491e9b0f887.png)

**Comment by JKorf** [comment]
See #1007 , this has been fixed in the latest version.
Yes the common interface has changed. The common spot client is accessible like this in the latest version:
`var commonClient = binanceClient.SpotApi.CommonSpotClient;`
See also this:
https://jkorf.github.io/CryptoExchange.Net/Migration%20Guide.html#iexchangeclient

**Comment by heavymanto** [comment]
ok, thaks, but where i found Interface enum like this?

![image](https://user-images.githubusercontent.com/6449169/155762492-318a5bd5-1571-4db1-bc68-ebe6439fe9dd.png)

**Comment by heavymanto** [comment]
cool, but where i found this definitions?

![image](https://user-images.githubusercontent.com/6449169/155763608-41d30738-c142-43e0-a65d-73b03cf45548.png)

**Comment by heavymanto** [comment]
I have studied this new release and I must say that it is really well done. It is clean and very intuitive, a great architecture. Thanks for the much work you have done.
