### ISSUE TITLE
Error: Precision is over the maximum defined for this asset.

### ISSUE THREAD

**Issue by deewelop** [JKorf/Binance.Net#1021]
i have this problem :(
im sending a buy request in futures binance with Binance.Net, this code:

price = 90.22
qty = 0.2 //18$

client.FuturesUsdt.Order.PlaceOrder
(
"LUNAUSDT",
OrderSide.Buy,
OrderType.Limit,
qty,
null,
TimeInForce.GoodTillCancel,
null,
price
);

then shows me error "Precision is over the maximum defined for this asset."
that qty, i test it till 0.9 LUNA have same problem and it works with qty 1 LUNA
1 LUNA = 90$ !!!
really minimum trade quantity is 90$? or problem is somewhere else?

my guess

1. probably in dll you will Multiplication and division or somthing like that on order size or price, and in that process it will create a lot of Precision in that value you are sending to binance...

2. you are checking and verifying binance rules for positions yourself before sending to binance with a outdated document and it have wrong maximum Precision for some assets

or really have this limit at least 90$ for trade? in binance original its 10$ i think :( so what's problem?
idk, just help me fix it, its pain :(
thanks <3

**Comment by HypsyNZ** [comment]
https://github.com/JKorf/Binance.Net/blob/ea92ab4fb9733bb01fdfef8f6c1e8b5aee99e153/Binance.Net/Clients/SpotApi/BinanceClientSpotApi.cs#L107-L116

This isn't a solution as such but you could comment out these lines and manage the trade rules yourself

**Comment by mange-ess** [comment]
@deewelop, the error message you are receiving is because Binance has a trading rule for LUNAUSDT which only allows you to specify quantity in integer LUNAs. This is why you are able to place an order when you enter 1 LUNA, but not 0.2, 0.3, 0.4 ... 0.9 . So yes, your minimum trade quantity for LUNAUSDT is 1 LUNA = currently around 92 USDT.

When I check the web portal for trading LUNAUSDT, the same rules apply there,

The precision can vary from one symbol to another, e.g. if you look at BTCUSDT you can place orders of 0.001 BTC.

If I'm not mistaken, the trading rules for all the symbols of the USD futures exchange can be fetched using:

`var result = await _tradingClient.UsdFuturesApi.ExchangeData.GetExchangeInfoAsync();`

And then checking the `result.Data.Symbols` collection for QuantityPrecision etc.

**Comment by deewelop** [comment]
Ye its binance itself rules i guess :(
thanks <3
