### ISSUE TITLE
SpotStreams.SubscribeToKlineUpdatesAsync doesn't give updated data

### ISSUE THREAD

**Issue by Nmaster88** [JKorf/Binance.Net#1043]
After using this method, which calls the callback from time to time, i noticed that it is not correctly updating the data it gives in the callback.

For example i'm using the method like this:

```
            socketClient.SpotStreams.SubscribeToKlineUpdatesAsync("BTCUSDT", Binance.Net.Enums.KlineInterval.OneMinute, data =>
            {
                if (data.Data.Data.Final || DateTime.Now > data.Data.Data.CloseTime)
                {
                    Console.WriteLine($"----------------------------------------------------------------------------");
                    Console.WriteLine($"Beginning time: '{data.Data.Data.OpenTime}', beginning price: '{data.Data.Data.OpenPrice}'");
                    Console.WriteLine($"Closing time: '{data.Data.Data.CloseTime}', closing price: '{data.Data.Data.ClosePrice}'");
                    Console.WriteLine($"----------------------------------------------------------------------------");
                    // some method i use
                }
            });
```

Now if i look into the console:
![image](https://user-images.githubusercontent.com/12272451/160703262-8eceb894-7252-4547-9c32-25f7b3f22e1e.png)

In this case by luck the close price is updating, but the rest we can see that is always the same value. OpenTime, OpenPrice, CloseTime and so on.

Is there any workaround?

**Comment by HypsyNZ** [comment]
Did you figure out what you are doing wrong yet

**Comment by HypsyNZ** [comment]
What would you expect to happen and why? Please explain step by step.

**Comment by Nmaster88** [comment]
Maybe i don't understand well how this works,

What i see happening, is that, for example if i choose OneMinute i'm expecting that after one minute i would get a different opening and close price, and open time and close time and not something that seems to be fixed and the only thing i see changing is the close price.

Is this how it is supposed to work? If yes, this is not an issue.

**Comment by JKorf** [comment]
What many people are getting confused about is that the updates don't come in once for each kline for the time interval you subscribed to, but rather it keeps updating the latest kline every time something changes. The updates are always talking about the latest kline, and when a trade happens that kline has a different Close price because at that point the close price of the kline is the last traded price. 

When you're using the 1 minute interval and a new kline is started you'll get new data for the new minute, and then for one minute you'll get updates for that kline.

Hope that clears it up a bit
