### ISSUE TITLE
A desire to bringing the orders properties types in accordance to each other

### ISSUE THREAD

**Issue by Kirill2Kirill** [JKorf/Binance.Net#1119]
All orders in Binance are reduced to two types: BinanceOrderBase and BinanceStreamOrderUpdate.
Is it possible to bring their matching properties types to the same denominator? 
If in one int bool?, then in the other it should be bool?
For example:
bool? IsWorking;
bool IsWorking;

**Comment by HypsyNZ** [comment]
> If in one int bool?, then in the other it should be bool?

Why?

**Comment by JKorf** [comment]
Cleaning up old issues, if you feel this issue is still relevant feel free to comment.
Altough it's a valid point, it doesn't always work that way in the API. If the endpoint always returns true/false but the update is sometimes null then I think it's correct to have different nullability for the two.
