### ISSUE TITLE
GetExchangeInfoAsync() on V8.0.11

### ISSUE THREAD

**Issue by lploumen** [JKorf/Binance.Net#1130]
Hi,
I made an application a few months ago, that was working fine.
Now when I start it, it starts with :

``
var exchangeInfoResult = await m_BinanceClient.SpotApi.ExchangeData.GetExchangeInfoAsync();
``
Then the exhangeInfoResult above does not succeed:

![image](https://user-images.githubusercontent.com/11539944/182044927-db490b51-d52c-44a3-8397-5bc494742def.png)

So, do I have to update the app ? If so, why? I haven't seen any changes in the exchangeinfo api.  Is there a way to maintain compatibility ?

**Comment by JKorf** [comment]
Hi, the issue here is that Binance added the TRD_GRP_004 permission group. Due to how the deserialization was handled (using a JsonItemConverter instead of a normal converter) this threw an error on the new unknown enum value.

This has been fixed in a later version, and changes have been made to prevent this from happening again when a new value is added.
