### ISSUE TITLE
Side is missing in GetUserTradesAsync()

### ISSUE THREAD

**Issue by Maddest** [JKorf/Binance.Net#1266]
Hi,
I'm using the SPOT function GetUserTradesAsync() and realized the output parameter 'side' is missing. Is this on purpose?
Thanks, Bernd

**Comment by JKorf** [comment]
Hi, this is the API doc for that endpoint: https://binance-docs.github.io/apidocs/spot/en/#account-trade-list-user_data
As you can see it is also not available there. This is probably because `side` can be confusing as there is always a buy and a sell side to a trade. Instead there is a IsBuyer and IsMaker property which you can use

**Comment by Maddest** [comment]
OK, thank you for the quick reply. So, I assume if 'IsMaker' = true, then it was a sell from my side.

**Comment by glipitch** [comment]
No, IsBuyer being true or false means you were the buyer or seller respectively. IsMaker relates to whether you are the maker or taker - see https://www.binance.com/en/support/faq/what-are-market-makers-and-takers-360007720071

**Comment by Maddest** [comment]
Thanks for clarifying this for me

**Comment by Maddest** [comment]
Thanks for clarifying this for me
