### ISSUE TITLE
WebSocket are not supported on Windows 7

### ISSUE THREAD

**Issue by ArcCosec** [JKorf/Binance.Net#1299]
Hello and thanks for the great library.
But there is a problem. When I try to subscribe to market data, I get the exception "The WebSocket protocol is not supported on this platform." I have Windows 7.
Please help me solve this problem. Maybe for Windows 7 you can use WebSocket4Net or something similar?

**Comment by JKorf** [comment]
Hi, Windows 7 is not supported anymore by Microsoft or by this library for the exact reason you mentioned. Supporting the very small and shrinking group of people still running Windows 7 is not something I have time for unfortunately.  

I'd recommended updating the OS. Alternatively you could go very far back in this libraries history and get a version which was actually using WebSocket4Net but you'd have to manually update it to support any API changes since that time.

**Comment by ArcCosec** [comment]
Thanks for your answer. Please tell me how to go back to the history of this library and get the version with WebSocket4Net.

**Comment by NoParamedic** [comment]
Web Sockets on Windows 7 are a serious security risk and their use should be discouraged and even deliberately unsupported even if it breaks existing applications.
