### ISSUE TITLE
I'm getting timestamps 1000ms ahead of server time using AutoTimestamp

### ISSUE THREAD

**Issue by dporterty** [JKorf/Binance.Net#139]
2018/09/26 22:43:36:595 | Info | Time offset set to 1542.7305ms
2018/09/26 22:43:36:801 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

Most requests have no issues, however I am getting this in some instances.  Would it be possible to change the code so that if the time offset were greater than 1000ms it could adjust the offset to resolve this?

Edit: wording...

**Comment by JKorf** [comment]
Hi, 
The offset of local time + server time is calculated by taking the local time - the server time, plus the time of a round trip request divided by 2 (single trip). If the round trip takes longer during the calculation then when doing an actual request the timestamp isn't correct. 

Say the local time is 20:00:00,0 and server time is 20:00:05,0, and a round trip request takes 2 seconds during the calculation, then the timestamp offset is calculated at 5 + (2 / 2) = 6 seconds. Now in the next request if it only takes 0.5 seconds the timestamp is ahead of the server time since then we tell the server the timestamp of the request is 20:00:06,0 even though the server time is only 20:00:05,5.

Do you have a suggestion for this problem?

**Comment by JKorf** [comment]
Hi, this should be fixed in the latest version. I removed the calculation of a round trip since it proved to be inconsistent on unstable ping. Let me know if you still have issues.
