### ISSUE TITLE
System.Text.Json serialization of BinanceSpotAccountSnapshot and member types has changed in version 10.0.0

### ISSUE THREAD

**Issue by glipitch** [JKorf/Binance.Net#1399]
Example: 

GetDailySpotAccountSnapshotAsync serializes to the following JSON for the date 2024.07.25

**10.0.0**

[{"updateTime":1721951999000,"type":"SPOT","data":{"totalAssetOfBtc":0.01882757,"balances":[{"asset":"ADA","free":0,"locked":1252.9,"Total":1252.9},
[truncated]

**9.11.1**

[{"Timestamp":"2024-07-25T23:59:59Z","Type":0,"Data":{"TotalAssetOfBtc":0.01882757,"Balances":[{"Asset":"ADA","Available":0,"Locked":1252.9,"Total":1252.9},
[truncated]

**Comment by JKorf** [comment]
Hi, this is a by product of the change to System.Text.Json. Previous situation was that only some of the object properties had a Newtonsoft.Json `[JsonProperty("..")]` attribute, while now each property has a System.Text.Json `[JsonPropertyName("..")]`. You're probably using System.Text.Json to serialize the object so that's why it's changed.

I'd argue the current version is now 'more' correct since it will be serialized to the same names as it was deserialized from.

**Comment by glipitch** [comment]
OK. I've been using System.Text.Json exclusively for a few years, and have several years of disk-persisted snapshot data. I'll modify my historical data to match the new format. Thanks for your reply.

**Comment by JKorf** [comment]
I see, I appologize for the inconvenience, I didn't think about this case. Although it's not necessarilly a function of the library I am aware that some users do this.
Anyway, it shouldn't be changing again.

**Comment by glipitch** [comment]
No problem. I took a risk by having my data depend on third-party types. I'll not let it happen again. Thanks @JKorf.
