### ISSUE TITLE
returning error ClientOrderID from function PlaceOrderAsync after upgrading to Version 10.13

### ISSUE THREAD

**Issue by dante1989** [JKorf/Binance.Net#1454]
Dim ItemStopBinance = Await clientFutureBinance.CoinFuturesApi.Trading.PlaceOrderAsync
Msgbox(ItemBuyLongBinance.Data.ClientOrderId)
I got the return ClientOrderId is "**hRGr9VkSWrda1daWobrX32tA**"

But the correct ClientOrderId is: "x-d63tKbx3JK**hRGr9VkSWrda1daWobrX32tA**"  (I have checked the correct ClientOrderId from function GetOrdersAsync and GetOpenOrdersAsync)

**Comment by JKorf** [comment]
Hi, since you're running into some issues here I'll give you some background on what change was introduced where some logic around this was changed.

When placing an order a reference id is attached to the order, which is used by the exchange to give a small amount of rebates to the referenced acccount (me). This is paid by the exchange, not the user so there is no harm in this. The reference id is added by using the `clientOrderId` field and adding the `x-d63tKbx3JK` value to it when placing an order.

Previously this was only done when the user provided no clientOrderId value in the order placement so the value could safely be set. 

This was changed recently to also check if the reference id could be added to the user provided clientOrderId parameter while still being valid according to the exchange rules. This functionality is behind the `AllowAppendingClientOrderId` flag in the client options and disabled by default.
However, to make this work seamlesly for the user the return value in the `ClientOrderId` response models should be the originally client  order id, without the client reference. 
So I introduced a json converter for this to remove the reference id again from the ClientOrderId property during deserialization of the response model.

This is, as far as I'm aware, working correctly. In your case I would expect the GetOrdersAsync  and GetOpenOrdersAsync response models to have removed the `x-d63tKbx3JK` prefix from the ClientOrderId properties in the actual response model. Can you confirm that?

**Comment by dante1989** [comment]
When i use GetOrdersAsync and GetOpenOrdersAsync . I got the ClientOrderId including x-d63tKbx3JK.
So can i use AllowAppendingClientOrderId to get x-d63tKbx3JK?

**Comment by JKorf** [comment]
AllowAppendingClientOrderId is an option in the client settings, same place where you set the API credentials.

However, that wouldn't fix the issue you described.

I've just tried this:
```csharp
var order = await restClient.CoinFuturesApi.Trading.PlaceOrderAsync(
    "ETHUSD_PERP",
    Binance.Net.Enums.OrderSide.Buy,
    Binance.Net.Enums.FuturesOrderType.Limit,
    5,
    price: 3700,
    timeInForce: Binance.Net.Enums.TimeInForce.GoodTillCanceled,
    positionSide: Binance.Net.Enums.PositionSide.Long
    );

var orderData = await restClient.CoinFuturesApi.Trading.GetOrderAsync("ETHUSD_PERP", order.Data.Id);
var openOrder= await restClient.CoinFuturesApi.Trading.GetOpenOrdersAsync("ETHUSD_PERP");

var cancel = await restClient.CoinFuturesApi.Trading.CancelOrderAsync("ETHUSD_PERP", order.Data.Id);
```

All the ClientOrderId properties are returning the value without the `x-d63tKbx3JK` prefix as expected, so I'm not sure how you're seeing a different result.

**Comment by dante1989** [comment]
when AllowAppendingClientOrderId = False and Version 10.13:
I use GetOpenOrdersAsync, i got this:
![image](https://github.com/user-attachments/assets/0733ea22-9900-4514-8365-e7d16ec0f6d1)
I use GetOrdersAsync , i got this:
![image](https://github.com/user-attachments/assets/048bcf3a-c554-4751-83c8-1ca5c7756fea)
Most of orders including x-d63tKbx3JK
Only one order without the x-d63tKbx3JK prefix

**Comment by dante1989** [comment]
and when AllowAppendingClientOrderId = True and Version 10.13, i got the same issue I described.
I use GetOpenOrdersAsync, i got this:
![image](https://github.com/user-attachments/assets/a72942bb-1f14-4f36-9f9b-b738ca7838e5)

I use GetOrdersAsync , i got this:
![image](https://github.com/user-attachments/assets/dd875bb6-ebb1-4f67-ba50-d29e6789a014)

Some orders including x-d63tKbx3JK. Some orders without the x-d63tKbx3JK prefix

**Comment by JKorf** [comment]
Can it be that the orders that still have the x-d63 prefix have been placed from either another application using an older version of the library or the orders already existed and were placed with a previous version of the library?

The orders which still have the prefix in your overview have a prefix of `x-d63tKbx3` which indicates it was placed with an older version, the newer version uses `x-d63tKbx3JK`, and those are values which get replaced correctly it seems.

**Comment by JKorf** [comment]
@dante1989 Is this working correctly for you now?

**Comment by dante1989** [comment]
I often use the saved clientdordeid to retrieve orders data as well as when canceling orders. Currently I'm updating my Bot to use an alternative ID for clientdordeid to avoid data reading errors after this new update.

**Comment by dante1989** [comment]
"When placing an order a reference id is attached to the order, which is used by the exchange to give a small amount of rebates to the referenced acccount (me). This is paid by the exchange, not the user so there is no harm in this. The reference id is added by using the clientOrderId field and adding the x-d63tKbx3JK value to it when placing an order."
I understand that if there is a prefix x-d63tKbx3JK, the exchange will pay part of fee for the library developer (that's you). Therefore, I will keep this prefix for you.

**Comment by JKorf** [comment]
Appreciated. Yes, it's the same way for OKX, just with a different code.

**Comment by dante1989** [comment]
How much % will the exchange support you from transaction fees? I just want to know for reference because I often work with exchanges, maybe some exchanges do not have support policies, I will talk to them for you. Or you can message me via email admin@trungvanhoang.com. Thank you
