### ISSUE TITLE
Can I use parameter 'useServerTime' instead 'recvWindow'?

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#153]
https://github.com/jaggedsoft/node-binance-api/issues/68

**Comment by JKorf** [comment]
This is the same as setting the AutoTimestamp property to true in Binance.Net. This will synchronize the local machine time with the server time. 
The receive window is still a valid parameter then, because you still might want to timeout a request if it takes longer than 5000 seconds to arrive at server/process.
