### ISSUE TITLE
Binance API Trading Rules

### ISSUE THREAD

**Issue by xoxubepeso** [JKorf/Binance.Net#178]
hello @JKorf.
There are some updates in api trading rules, Can you please add them to lib?
https://support.binance.com/hc/en-us/articles/115003235691

Thanks in advance.

**Comment by JKorf** [comment]
Hi, thanks for the update. I'm probably not going to do anything with these rules though. 
It would require the library to keep track of the amount/type of order the user has outstanding, which isn't something I think a wrapper should do. The other rules the wrapper does check (related to order amount/price) are things which are easy to check and don't change often. 

The order information can't be cached because if a user also places orders via the website the information won't be up to date.

Let me know what you think.

**Comment by nikkozp** [comment]
This Trading Rules avalible in API. It is enough to make one request before the start

https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#account-api-trading-status-user_data

**Comment by JKorf** [comment]
Hi, I've added the call to request the trading status. I think it's up to the user self to keep track of this though.
