### ISSUE TITLE
OrderInfoUpdate callback supresses exceptions

### ISSUE THREAD

**Issue by HugoPeters1024** [JKorf/Binance.Net#179]
When second argument of BinanceSocketClient.SubscribeToUserStream, namely the Action<OrderInfoUpdate> throws an exception, there is no sign of it what so ever. I spent a really long time figuring out why my code execution stopped :/

I wonder if this is the prefered way to handle such problems. Wouldn't you want to rethrow the exception?

**Comment by JKorf** [comment]
Hi, the problem is that its not the same thread, so you if I'd re-throw you'd have to handle it somewhere in an UnhandledExceptionHandler callback, which isn't ideal either. Anyway, I've changed it so that the object returned from the Subscribe methods now also have a Exception event in addition to the ConnectionLost/ConnectionRestored events. You can subscribe to that to listen for exceptions.

Also you could of course use a try/catch inside the action. Note that the exceptions also always get logged, so you should check the output as well.

**Comment by HugoPeters1024** [comment]
Awesome thanks! I did indeed solve it with a large try, catch. Guess I'm
not that used to multithread exception handling yet. The help is much
appreciated!

Op vr 1 feb. 2019 21:15 schreef Jan Korf <notifications@github.com:
