### ISSUE TITLE
-1022: Signature for this request is not valid.

### ISSUE THREAD

**Issue by decutaxiyu** [JKorf/Binance.Net#213]
Hi. I received this error - 1022: Signature for this request is not valid.
 
client = New BinanceClient(New BinanceClientOptions() With {
                                   .ApiCredentials = New ApiCredentials("",  ""),
                                   .AutoTimestamp = True})
Dim accInfo As CallResult(Of BinanceAccountInfo) = client.GetAccountInfo()

**Comment by burakoner** [comment]
Don't use Api Key? Is it for public request or did you delete for privacy? If you request for public endpoint you can't use empty credentials. You can fix by not to provide API credentials. (Empty causes error). Otherwise if you clean API key for privacy, Binance deleted all API keys yesterday. Be sure your API key is valid.

**Comment by decutaxiyu** [comment]
API isn't valid.
