### ISSUE TITLE
Combined Streams

### ISSUE THREAD

**Issue by Danford** [JKorf/Binance.Net#225]
According to [Binance Offical API Documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md), there's an endpoint provided for combined streams. So say for instance I want to connect to many individual streams but instead of opening multiple, I open one stream that contains all the combined events for each stream. I've looked for implementation of this feature in Binance.Net and can't find anything utilizing this feature but maybe I'm overlooking it. If this exists could you please point me in the right direction and if it does not do you have any intentions of implementing it? I would be happy to lend a hand if help is needed.

`
Combined streams are accessed at /stream?streams=<streamName1>/<streamName2>/<streamName3>
`
`
Combined stream events are wrapped as follows: {"stream":"<streamName>","data":<rawPayload>}
`

**Comment by JKorf** [comment]
The combined streams are being used, but only if multiple symbols are subscribed at the same time. The subscribe methods allow multiple symbols to be passed in a single call, which will all subscribe on the same socket using the combined stream. (you might have already found this since you closed the issue)
