### ISSUE TITLE
Binance Futures

### ISSUE THREAD

**Issue by falifalifali** [JKorf/Binance.Net#240]
Hi.
Is there any plans to add Binance Futures API?
Official API Documentation - https://binanceapitest.github.io/Binance-Future-API-test-doc/

**Comment by JKorf** [comment]
Hi, no planning for it yet, but I want to add support for it when I have time.

**Comment by falifalifali** [comment]
> Hi, no planning for it yet, but I want to add support for it when I have time.

thanks

**Comment by nikkozp** [comment]
Binance Futures is almost identical to Binance Spot / Margin. But at the moment I don't see ideas as it is competent to add. We need to change the structure of the library so that we can inherit and override some functions. Already I am engaged in this question, and I want to send PR in the next week.

**Comment by Caglar35** [comment]
We are waiting for your support about binance futures JKorf.
Thanks.
