### ISSUE TITLE
Add supporting of futures API

### ISSUE THREAD

**Issue by ExaurovNM** [JKorf/Binance.Net#246]
Hi! I didn't find API for futures market and want to extend Client with it. 
How do you think, what is the best way to organize this:
1) Use existing client;
2) Create a new one.
Will be glad to hear your opinion.

**Comment by captholley** [comment]
Any word on when this might be available, if at all? Thanks!

**Comment by JKorf** [comment]
I want to add this, but I currently don't have the time to work on it. Some people did some work experimenting the library for use with the Futures API at #247, but I'm not sure if any progress is (being) made.

**Comment by captholley** [comment]
I have a working version of this where I have created a separate client for the futures api. I am going to look to merge this to the existing repo over the coming weeks. I have a question as to how this should be organized:

Seeing as a lot of the api calls for the futures are the same as the margin (just with a different base URL), should it be constructed using completely different methods, such as GetAllTickerSymbols and GetAllFutureTickerSymbols? Or would it be better to have one method call, with a Boolean option for futures (I.e. true for futures, default false otherwise). 

Let me know what you think and I will get it together. Hopefully I can have this ready relatively quickly after this is decided.

**Comment by shotyme** [comment]
Any progress here? I'm very interested in features enhancement as well.

**Comment by captholley** [comment]
I have started working on this (finally). I have created a new fork which you can follow [here](https://github.com/captholley/Binance.Net). I have completed the changes needed to the options in order to support the different urls, and have completed some of the rest requests that use the same endpoints. I will look to finish the rest of those this week and move on to the websocket edits. Hopefully will be able to push this at the end of next week.

**Comment by captholley** [comment]
See number #279

**Comment by JKorf** [comment]
I've pushed an alpha version of the futures API to Nuget, version 5.1.0-alpha. For anyone intrested in the futures API, please try it and report any issues you find. 

Thanks to @captholley for the work on this.
