### ISSUE TITLE
a Question about GetMyTrades

### ISSUE THREAD

**Issue by Kabundscha** [JKorf/Binance.Net#25]
Hello,
I have a small Question, is it Possible to get only the newest Trade Infos from a specific Symbol in a Console Application?

what i mean,
---> var myTrades = client.GetMyTrades("XVGBTC", 10, "Here; LAST 1 HOUR newest Results");

So the Symbol is XVGBTC, last 10 or more Results/Trades in the Last 1 hour.. 
Because with "10-max number of Results" its only the oldest Trades from the specific Symbol, why not the newest? Or is my thinkig wrong? ;x

**Comment by JKorf** [comment]
GetMyTrades returns the newest trades within the limit. If you pass limit: 10 as parameter it will only return the last 10 trades for that symbol. 

If you only want to receive the trades that happened since the last time you requested the info you can use the fromId parameter. If you pass the id of the most recent trade you got last time you requested you will only receive trades that have happened after that specific trade:
````C#
var initialResult = client.GetMyTrades("LRCBTC"); // Get initial data
Thread.Sleep(1000*60); // Wait for some period
var newTrades = client.GetMyTrades("LRCBTC",fromId: result.Data.Last().Id); // Get data after the last trade from last request
````

**Comment by Kabundscha** [comment]
Thank you, that is what i needed :)
