### ISSUE TITLE
ETHBULLUSDT is not a valid Binance symbol. Should be [QuoteCurrency][BaseCurrency], e.g. BTCUSDT

### ISSUE THREAD

**Issue by swAucxis** [JKorf/Binance.Net#268]
When calling the method
"Binance.Net.BinanceSocketClient.SubscribeToKlineUpdates(string symbol, KlineInterval interval, Action<T> onMessage)" I receive the following error.

"ETHBULLUSDT is not a valid Binance symbol. Should be [QuoteCurrency][BaseCurrency], e.g. BTCUSDT"

But I think ETHBULLUSDT is a correct symbol. The regex only doesn't allow it.

**Comment by nikkozp** [comment]
@swAucxis PR #269

@JKorf Why u added this `Regex `in `ValidateBinanceSymbol`? I think this is useless, especially when listing coins

**Comment by nikkozp** [comment]
and it would be correct `[BaseCurrency][QuoteCurrency]` :)

**Comment by JKorf** [comment]
@nikkozp You're right, it's not working out that great to have that check in. The idea for me was that when using multiple of my libraries its sometimes confusing as to what format they expect symbols to be in. For example Bittrex uses BTC-USD while Bitfinex uses tBTCUSD. 

While using multiple different exchanges I tend to forget which one expects what, so I added a check to validate the input and tell me what it should be if it isn't correct.

Maybe it should just be added to some documentation somewhere though. Or maybe you have some other idea?

**Comment by nikkozp** [comment]
@JKorf 
Personally, my opinion is the following:
1. Each exchange has its own name of coins, and if you want to check them in some way for a match, it is better to use the intermediary class between libraries and compare the name of coins there. Instead of checking it in the `Binance `library:) ~
2. It is best to minimize any checks when `tradeRules` is `disabled`. For example, I need to place an order as quickly as possible, and the library spends time on unnecessary data verification.

**Comment by JKorf** [comment]
@nikkozp I'm not sure how your suggestion in point 1 is better than whats happening now? Could you elaborate?

@swAucxis I've pushed a new version which has a fix with thanks to @nikkozp, it should be available in a few minutes on Nuget.

**Comment by nikkozp** [comment]
@JKorf 
To be honest, I don't quite understand why need to do verification using Symbol.

If we are talking about checking whether the user entered the Symbol correctly, then let the user himself check through SymbolsInfo, since Symbol is a dynamic parameter that can change depending on the Listing / Delisting.

If we are talking about finding the same symbols, for example for arbitrage between exchanges, then to check the correctness of the symbol, I would use an intermediate class between libraries to find an identical symbol, for example, between BTC-USD and tBTCUSD

You know what I mean?

**Comment by nikkozp** [comment]
I see in the code that you request GetExchangeInfoAsync when using TradeRules, so why not just check the symbols using `SymbolsInfo `instead of `Regex `?

**Comment by swAucxis** [comment]
Just to confirm. The latest version fixes the issue.
