### ISSUE TITLE
how to detect api available coin

### ISSUE THREAD

**Issue by redquantum** [JKorf/Binance.Net#289]
Hello Dear Friend,

Some new coin on binance API not working. For example coin 12H data available but not stream data on API. How can I detect API data stream support coin? 

for example coin on binance website 12h has trading and data available, rsi etc. But does not support API stream socket data for coin. I want to connect 1min and 1h socket.In fact, socket connect available,but not stream data in socket. Simply I want to detect  stream data has on API available or not on coin, without connecting.

Thank you.

**Comment by nikkozp** [comment]
Hello @redquantum , when you subscribe to a socket that involves getting data on all points ( for example `SubscribeToAllSymbolTickerUpdates`). Then you can easily find a new coin by checking it with your list of available coins (`GetExchangeInfo`). After finding this coin can freely subscribe to all of its sockets. Due to the fact that the coin is new , some data may come later.
