### ISSUE TITLE
wrong order of bids in FuturesSocketClient

### ISSUE THREAD

**Issue by spbsmile** [JKorf/Binance.Net#297]
i use 5.1.0-alpha8
i call 
var s = client.SubscribeToOrderBookUpdates(symbol, 500, OrderBookUpdate);

![image](https://user-images.githubusercontent.com/4917689/77586563-7b219f80-6ef7-11ea-8261-3f82d8913666.png)

First price is the lowest  - this is a mistake.

**Comment by nikkozp** [comment]
Its a `Different Book Depth Streams`

**How to manage a local order book correctly**

1. Open a stream to wss://fstream.binance.com/stream?streams=btcusdt@depth.
2. Buffer the events you receive from the stream. For same price, latest received update covers the previous one.
3. Get a depth snapshot from https://fapi.binance.com/fapi/v1/depth?symbol=BTCUSDT&limit=1000 .
4. Drop any event where u is < lastUpdateId in the snapshot.
5. The first processed event should have U <= lastUpdateId AND u >= lastUpdateId
6. While listening to the stream, each new event's pu should be equal to the previous event's u, otherwise initialize the process from step 3.
7. The data in each event is the absolute quantity for a price level.
8. If the quantity is 0, remove the price level.
9. Receiving an event that removes a price level that is not in your local order book can happen and is normal.

**Comment by nikkozp** [comment]
It works correctly for me

**Comment by spbsmile** [comment]
oh how difficult)
I will return to this problem in the evening in Moscow
thx!

**Comment by spbsmile** [comment]
You did not understand me!

bid - first price is max of array prices
ask - first price is min of array prices
proof - postman:
![image](https://user-images.githubusercontent.com/4917689/77683937-44f12800-6faa-11ea-9d0f-ebef782bd751.png)


your nuget solution: 

![image](https://user-images.githubusercontent.com/4917689/77684193-aa451900-6faa-11ea-8320-521978d2f546.png)


how fixed this problem ??

**Comment by nikkozp** [comment]
With this socket, you don't get the actual values in the depth you only get the data that needs to be changed.

In your case you can use `SubscribeToOrderBookUpdatesAsync`

**Comment by spbsmile** [comment]
its the same

![image](https://user-images.githubusercontent.com/4917689/77730913-dd22f780-7012-11ea-864f-dbf9984e7c6c.png)

ок i switch to rest api. 
via socket api how get top current bid ask - I do not know.

**Comment by jkorf-bloemert** [comment]
If you just want to receive the full order book every update you need to use the SubscribeToPartialOrderBookUpdates method. That will give you the full order book on each update but it is limited to the top 5/10/20 entries. 

The SubscribeToOrderBookUpdates method subscribes to an orderbook only, but makes it possible to keep track of the full order bookk.

**Comment by JKorf** [comment]
You need the SubscribeToPartialOrderBookUpdates method, it subscribes to full order book updates, but is limited to 5/10/20 entries only.

The SubscribeToOrderBookUpdates method subscribes to changes to an order book only, but allows the full order book to be synchronized.

Have you also seen the BinanceSymbolOrderBook implementation? It provides the order book synchronization for you.
