### ISSUE TITLE
account stream

### ISSUE THREAD

**Issue by Cjay93** [JKorf/Binance.Net#31]
seems they have added a clause error now.

**Comment by JKorf** [comment]
Hi,

Currently Binance is having some technical problems (https://twitter.com/binance_2017). All trading is suspended.

Whenever I call StartUserStream the server returns `An unknown error occured while processing the request`. So that's where your code might be crashing. 

Not much I can do atm, Binance has to fix their service.

**Comment by Cjay93** [comment]
Ok that makes sense. Was just wondering if it was a problem in my new code.
Thanks

**Comment by JKorf** [comment]
This should be fixed by now
