### ISSUE TITLE
socket ping / pong

### ISSUE THREAD

**Issue by thomasd3** [JKorf/Binance.Net#349]
Binance is sending a ping at regular interval, is the library sending back a pong automatically?

**Comment by JKorf** [comment]
Socket pings are automatically responded to. Are you having issues?

**Comment by thomasd3** [comment]
At first, I tried to set a low timeout; since I'm reading book data, I put 10s as the limit for which no data is received. Although data kept coming, I kept getting the message that no data has been received in time and the socket would get reset.

That's the settings I used (F#):

    socketOptions.AutoReconnect         <- true
    socketOptions.ReconnectInterval     <- TimeSpan.FromSeconds(2.)
    socketOptions.SocketResponseTimeout <- TimeSpan.FromSeconds(5.)
    socketOptions.SocketNoDataTimeout   <- TimeSpan.FromSeconds(10.)

**Comment by JKorf** [comment]
Hi, can you share some code where the problem exists? Just creating a socket with those settings and subscribing to book updates works fine for me.

As a side note; `SocketNoDataTimeout` was mainly introduced for socket API's where there's a heartbeat mechanism. For example; Bitfinex sends a heartbeat message every 15 seconds, so when you haven't received anything in 20 seconds you know something is wrong. For API's who don't have a heartbeat it's harder to chose a correct timeout since on low volume symbols there just might nog be any update for 20 seconds while still fully connected.

Anyway, if there is data incoming it shouldn't reconnect, so if you could create a small snipper recreating the issue that would be great.

**Comment by thomasd3** [comment]
I will re-check it to see what happens.

**Comment by naserkaka** [comment]
Hi, does this library auto ping? or do I need to code it? in that case , how does the ping method look like? 
What if Binance send a stop-pong back that says I have to back off. How do I read the stop-pong from Binance? So I know when to stop streaming data. @JKorf

**Comment by JKorf** [comment]
I'm not sure what you're talking about to be honest. The low level websocket ping/pong frames are handled internally. I'm not sure what the stop-pong message is you're talking about.
