### ISSUE TITLE
Error 3

### ISSUE THREAD

**Issue by luukholleman** [JKorf/Binance.Net#390]
I have an issue where sometimes orders fail. The error object of CallResult doesn't really help me further.

Code: 3
Message: Server error: An error occurred while sending the request.
Data: null

How can I see what went wrong (what is error 3?) and how to fix it?

**Comment by walterX12** [comment]
Hi,

I am afraid you are not providing enough details to help. How do you reproduce the issue? Please provide sample code.
Error 3 does not seem to be Binance error https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md

**Comment by JKorf** [comment]
Error 3 is an internal library code, isn't specifically related to the error. Hard for me to say what the problem is based on the info, but I'm aware that's all the info you have. I've adjusted the error logging so in the next (beta) version (coming soon) you should have some more details on what went wrong.

**Comment by luukholleman** [comment]
Ok thanks, sounds good to pinpoint on what it could be.

For what it's worth, I also started using the kucoin variant and I also had it there 1 afternoon.

**Comment by JKorf** [comment]
Hi, the version 6.0.0-beta.4 should have some more detailed error info.

**Comment by JKorf** [comment]
Closing this for no response, if this is still an issue please let me know.
