### ISSUE TITLE
BinanceSymbolFilter

### ISSUE THREAD

**Issue by Serjster** [JKorf/Binance.Net#41]
Unless I'm missing something, the current implementation of `BinanceSymbolFilter` makes them fairly useless, for example, how am I supposed to access the properties I need for Lot Size?

    {
      "filterType": "LOT_SIZE",
      "minQty": "0.00100000",
      "maxQty": "100000.00000000",
      "stepSize": "0.00100000"
    },

**Comment by JKorf** [comment]
Hi, I'm not sure what the problem is? The values you pasted are the values which Binance will check your order on. It makes sure the order is a minimum of 0.001 in size, max 100000 and has has no more than 3 digits after the comma. If any of these check fails it will reject the order. 

You should therefor make sure your order complies to these rules. You can either just do this yourself, use the helper function `ClampQuantity` in `BinanceHelpers`, or set the `TradeRulesBehaviour` in the `BinanceClient` to `AutoComply` to automatically apply the filters for you.

**Comment by Serjster** [comment]
The problem is that those properties, `FilterType`, `MinQty`, etc do not exist on the `BinanceSymbolFilter` class... how can I access those values? Didn't know about the `TradeRules` deal, super helpful, thanks.

Are there any `Commission` helpers?

**Comment by JKorf** [comment]
I see what you mean now. `BinanceSymbolFilter` is a base class and has 3 implementations: `BinanceSymbolPriceFilter`, `BinaceSymbolLotSizeFilter` and `BinanceSymbolMinNotionalFilter`. You can get them from the list in a symbol using something like `Filters.OfType<BinanceSymbolLotSizeFilter>().FirstOrDefault()`.

Currently there are no Commission helpers. What would you expect of these?

**Comment by Serjster** [comment]
Just something to see what you'd be charged to do a transaction, in BNB or BTC would be helpful.

**Comment by JKorf** [comment]
No problem.

Calculating fees might be a bit hard. Without taking BNB into account the fee is 0.1% per trade, which is fine to calculate. However, if the account uses BNB to pay the fee with a 50% discount Binance uses this logic:
`
If the trade receivable is NEO, we will calculate it by the exchange ratio of NEO to BNB at the market price,  which is based on the market price of  NEO / BTC and BNB / BTC.

Exchange ratio of NEO/BNB = NEO/BTC[market price] /(BNB/BTC [market price]). Binance update cycle for the market price is 1 second.
`
I can't really implement this in the library since the library doesn't have any logic to have the current market prices, certainly not every second. So there would be no way to calculate it accurately, so I don't think I'll implement that.
