### ISSUE TITLE
Rename Volume properties

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Binance.Net#411]
Hi

At latest update u rename `QuoteVolume `to `TotalTradedAlternateAssetVolume`.

You can rename it back to `BaseVolume `and `QuoteVolume `for example?

In `BinanceSymbol`, we have `BaseSymbol `and `QuoteSymbol`, which is logical to understand. But what is `TotalTradedAlternateAssetVolume `is difficult to understand.

**Comment by JKorf** [comment]
I understand. I renamed it because on USDT-M futures the property means the quote volume, but on COIN-M the same property (same json key) means base volume. By using a shared name for it I was able to have a shared method and response model for both implementations.

Maybe calling the property `BaseOrQuoteVolume` or something alike with describing comment that it is diffent for Coin/Usdt futures would do?

Thoughts?

**Comment by nikkozp** [comment]
We can create a new class that inherits the base `Ticker `and redefine `BaseVolume `and `QuoteVolume `with the new json key and still use the same parameters and the same interface

```csharp
public class TickerUSDT : Ticker, ITicker
    {
         [JsonProperty("volume")]
        public new decimal BaseVolume { get; set; }
         [JsonProperty("quoteVolume")]
        public new decimal QuoteVolume { get; set; }
    }
```


```csharp
public class TickerCOIN : Ticker, ITicker
    {
         [JsonProperty("quoteVolume")]
        public new decimal BaseVolume { get; set; }
         [JsonProperty("volume")]
        public new decimal QuoteVolume { get; set; }
    }
```

we can do some of this?

**Comment by JKorf** [comment]
Yes, that's a possibility. 

Quite a lot of work though, since there are a lot of models which have base/quote volume and for each of them I have to make 2 sub-classes, an interface, take the method implementation from the base client and create a new method in both USDT and COIN sub-clients which return the specific sub-classes.

Still, it creates the cleanest interface, so I'll probably change it.

**Comment by JKorf** [comment]
Refactored in latest 6.0.0 version
