### ISSUE TITLE
BinanceSocketClient MissingMethodException

### ISSUE THREAD

**Issue by BenDavison** [JKorf/Binance.Net#428]
Hi,

  Is this a known issue or do you have a suggestion as to what it may be?  keys are correct as the order and balance data is in the response that is failing to deserialize.  I have also cleared out old packages and done a dotnet restore prior to a clean build to ensure this not dlls out of step. (note I am also raising an issue with the latest version of the Binance dll against the latest api which may also be related to Binance changing their signature).

  If I get  time I will attempt to debug this further but was hoping its in hand or a known easy fix?

2020/09/07 13:35:18:925 | Error | Socket 1 Exception during message processing
Exception: System.MissingMethodException: Method not found: 'CryptoExchange.Net.Objects.CallResult`1<!!0> CryptoExchange.Net.BaseClient.Deserialize(Newtonsoft.Json.Linq.JToken, Boolean, Newtonsoft.Json.JsonSerializer)'.
   at Binance.Net.BinanceSocketClient.<>c__DisplayClass63_0.<SubscribeToUserDataUpdatesAsync>b__0(String data)
   at CryptoExchange.Net.SocketClient.<>c__DisplayClass52_0`1.<AddHandler>g__InternalHandler|0(SocketConnection socketWrapper, JToken data)
   at CryptoExchange.Net.Sockets.SocketConnection.HandleData(JToken tokenData)
Data: {
  "e": "executionReport",
  ...

**Comment by JKorf** [comment]
Hi, It's because of a missmatch between the Binance.Net version and CryptoExchange.Net version. If you're using Binance.Net 5.1.14 you should use CryptoExchange.Net version 3.0.12. 
When using Binance.Net 6.0.0, CryptoExchange.Net 3.0.14 should be installed. 

This is just a temporary issue at the moment, I'll release stable version 6.0.0 soon, but it's taking a little longer than anticipated to get it ready.
