### ISSUE TITLE
BinanceFuturesClientOptions - CS0144 

### ISSUE THREAD

**Issue by Amannda123** [JKorf/Binance.Net#440]
After updating from 5.x to the latest release im currently rewriting my code... run into this:

This is fine: 
`var client = new BinanceClient(new BinanceClientOptions { LogVerbosity = LogVerbosity.Debug });`

This is it not:
`var futuresClient = new BinanceClientFutures(new BinanceFuturesClientOptions {LogVerbosity = LogVerbosity.Debug});`

CS0144 - Cannot create an instance of the abstract class or interface 

Also inconsistent after renaming stuff ...  to me it made more sense before the change

**Comment by Amannda123** [comment]
nvm found that its all combined...

**Comment by JKorf** [comment]
If you have any suggestions on naming or anything really, I'd be happy to hear it and consider changing it. I've made the choice to restructure the clients because 1. The BinanceClient class was getting way to big, with thousands of lines of code for all sort of calls and 2. Because I was adding support for COIN-M futures and I wasn't too big on adding another separate client which no-one knew existed.

With a single client for all rest calls people don't have to specifically know about any other clients, they can just explorer the API by looking at intellisense.

Again, if you have suggestions, let me know.
