### ISSUE TITLE
How to calculate historical Moving Averages from Klines Binance Futures?

### ISSUE THREAD

**Issue by mircofx** [JKorf/Binance.Net#446]
Hi. I can get 500 candles from Binance Futures. I need to calculate MAs for all the candles I got. How can I do it. I tried with a list but it didn't work. I need them to be displayed in the DatagridView on another column so I can automate orders based on the closing price and the previous MAs.

            using (var client = new BinanceClient())
            {
                DateTime time2 = client.FuturesUsdt.System.GetServerTime().Data;
                DateTime time1 = time2.AddHours(-500);

                var result = client.FuturesUsdt.Market.GetKlines("BTCUSDT", KlineInterval.OneHour, time1, time2);
                var Candles1h = result.Data.ToList();
                Candles1h = Candles1h.OrderByDescending(a => a.OpenTime).ToList();
                dgvCandles1h.DataSource = Candles1h;
                
            }

**Comment by thomasd3** [comment]
you define a period (x candles) and for each position, you average the x previous candles. The formula is here: https://en.wikipedia.org/wiki/Moving_average

That being said, moving averages lag a lot. Exponential moving averages are better since they represent better the latest data points, but they still lag a lot too.
They can be useful to visualize a trend, but if you use it to trigger orders you will certainly not make money because the trend could well have reversed before your moving average shows it. It can be useful with some markets which are slow, like stocks, but it's not useful for trading in volatile markets, like cryptos.

**Comment by mircofx** [comment]
I meant practically, I know what is an MA. I need a practical solution using my code. I know the difference between MA and EMA I don't care if they lag

**Comment by thomasd3** [comment]
There are different C# implementation here: https://stackoverflow.com/questions/12884600/how-to-calculate-simple-moving-average-faster-in-c
either through a code loop, or using LinQ
