### ISSUE TITLE
missing GetExchangeInfoAsync() and SubscribeToSymbolTickerAsync() methods in BinanceClient and BinanceSocketClient

### ISSUE THREAD

**Issue by LeonardoX77** [JKorf/Binance.Net#490]
I have updated
Binance.Net 4.0.1 to 6.3.2
CryptoExchange.Net 2.0.2 to 3.1.0

But I can't find GetExchangeInfoAsync() method in BinanceClient, even searching in the whole object explorer, where is it? how can I get the current list of asset pairs?
I also cleaned and rebuilt my solution but still same error

Also I can't find SubscribeToSymbolTickerAsync() method in BinanceSocketClient

Actually, with the previous versions I get an error BinanceClient.GetExchangeInfoAsync (see attached log file for more info):
5: Error deserializing data: Deserialize Unknown Exception: Object reference not set to an instance of an object

Any help would be appreciated
Thanks
[log_20201104.zip](https://github.com/JKorf/Binance.Net/files/5487391/log_20201104.zip)

**Comment by JKorf** [comment]
Hi, I've done some work splitting the client into separate parts to keep it maintainable. The methods you're looking for are here:
`client.Spot.System.GetExchangeInfo()`
`socketClient.Spot.SubscribeToSymbolTickerUpdates()`

I was able to parse the data you provided in the log just fine with the latest version, so that should be no problem anymore.

**Comment by LeonardoX77** [comment]
It works again.
Many thanks!
