### ISSUE TITLE
Binance.us capabilities?

### ISSUE THREAD

**Issue by jcjurevis** [JKorf/Binance.Net#494]
Does this project currently support Binance.us usages? I have tried with other Binance projects to change the endpoint/url to https://api.binance.us and it has only given me an error

**Comment by JKorf** [comment]
Hi, I'm able to retrieve basic data via the Rest API when changing the address, so I think that works correctly. The socket connection doesn't work for me even though it tries to connect to the correct address. I'm pretty sure that's not an issue witht he library though, might just be because I'm not in the US.

You can change the base API address in the client options:
````C#
            var client = new BinanceClient(new BinanceClientOptions()
            {
                BaseAddress = "https://api.binance.us",
                BaseAddressUsdtFutures = "xxx",
                BaseAddressCoinFutures = "xxx",
                ApiCredentials = new ApiCredentials("KEY", "SECRET"),
            });
````
