### ISSUE TITLE
Version Update very big problem

### ISSUE THREAD

**Issue by redquantum** [JKorf/Binance.Net#520]
Hello,
Why are your updates not supporting older versions? We have to rewrite the program with every update. If you are updating new, why not publish the old DLL and library under the name Old versions. I updated and the whole project is mixed.
Please publish the old DLL and library.

Thank you.

**Comment by JKorf** [comment]
Feel free to clone the repository and just use an older version in which you can fix things if a breaking change happens in the Binance API. That way you don't have to update to newer versions at all if you don't want to.

To keep the library maintainable I've had to do some restructuring, which I know breaks existing code. That's why I updated the version to 6.x.x from 5.x.x. When upgrading between versions you can expect some things to break. 

I develop and maintain this library in own free time, and frankly, it takes up quite a bit as it is. I don't have the time, nor the will, to keep older versions around and working.

As I said, you can just clone the repository and maintain the version you want on you own.
