### ISSUE TITLE
GetKlines Price Problem

### ISSUE THREAD

**Issue by allcasper99** [JKorf/Binance.Net#597]
hello, when I use the klines method, there is a problem with the incoming prices.
The prices of the Tradingview website and the binance exchange are the same, but the price from the method is different.
You can see in the attachment. Example icxusdt

Binance
![image](https://user-images.githubusercontent.com/77941443/107992331-8555fc00-6fe9-11eb-9e3f-3d967b28289b.png)

Tradingview
![image](https://user-images.githubusercontent.com/77941443/107992419-b9c9b800-6fe9-11eb-914b-42a0326e6b43.png)

Binance.Net GetKlines
![image](https://user-images.githubusercontent.com/77941443/107992596-162cd780-6fea-11eb-8c8c-a11948161988.png)

Can you fix this problem?

**Comment by Hulkstance** [comment]
The following code (same as yours) is retrieving the last candle which is unfinished. That's why the data is different. It changes over the time until the time interval is complete.

```csharp
await client.Spot.Market.GetKlinesAsync("ICXUSDT", KlineInterval.FourHour, limit: 1).ConfigureAwait(false);
```

If you want to pull the latest __finished__ candle you should do:

```csharp
await client.Spot.Market.GetKlinesAsync("ICXUSDT", KlineInterval.FourHour, limit: 2).ConfigureAwait(false).SkipLast(1).ToList();
```

Or you could just remove the last candle, instead of `SkipLast`.

**Comment by SARPSARP090** [comment]
Hi. 

await client.Spot.Market.GetKlinesAsync("ICXUSDT", KlineInterval.FourHour, limit: 2).ConfigureAwait(false).SkipLast(1).ToList();

Is SkipLast here obsolete?
