### ISSUE TITLE
Read JSON from Websocket

### ISSUE THREAD

**Issue by JMedon** [JKorf/Binance.Net#65]
Hi
I subscribed to websocket and I would like to read JSON in handle data section

var successDepth = socketClient.SubscribeToDepthStream("bnbbtc", (data) =>
            {
                // handle data
                Console.WriteLine(data);
            });

I received Binance.Net.Objects.BinanceStreamDepth message
How can I read raw JSON from websocket without any data prepariation.

Thanks

**Comment by JKorf** [comment]
Currently that is not possible. Any particular reason you would want this?

**Comment by JMedon** [comment]
I want to save raw JSON to file, can you share me information in which part of the code I should make my own method to save json to file?

thanks in advance

**Comment by JKorf** [comment]
I see.
You could change the data handler action from Action<BinanceStreamDepth> to Action<string> at
https://github.com/JKorf/Binance.Net/blob/76ef481f2c4679441123480ef994320efcc30ae8/Binance.Net/BinanceSocketClient.cs#L138
and remove the Deserialize call at 
https://github.com/JKorf/Binance.Net/blob/76ef481f2c4679441123480ef994320efcc30ae8/Binance.Net/BinanceSocketClient.cs#L147
so it returns the string instead of deserialized object.  That would do the trick.

**Comment by JKorf** [comment]
I'll assume you worked this out, if not please re-open the issue.

**Comment by thanasis-greece** [comment]
Hello! Is there any other way to take the websocket result in default/normal format (JSON) ? I am trying to get user balances in json format, not parsed.
I want to be able to get the results like they are in GET "https://api.binance.com/api/v3/account?" but I havent found any way to do that.
Also, I cant edit the code as I am using nuget package.

Thank you!
