### ISSUE TITLE
TransferSubAccountToSubAccount  - Signature not valid

### ISSUE THREAD

**Issue by milannovis** [JKorf/Binance.Net#674]
**Describe the bug**
This function is not working for me at all. 

**To Reproduce**
I have an api key that I use for trading on subaccount. it has all the permissions except for "margin" enabled. It is not working for me when I do "TransferSubAccountToSubAccount". When I try for example "TransferSubAccountToMaster" it works fine and when I try "TransferSubAccount" using different BinanceClient object (master account key) it works too.

**Expected behavior**
transfer the balance

**Debug logging**
"Data":null,"Error":{"Code":-1022,"Message":"Signature for this request is not valid.","Data":null},"Success":false

**Comment by Brendy88** [comment]
I tried to debug it and it seems that some of your requests are sent with query params and some with params included in the request body. Both "TransferSubAccountToSubAccount" and "TransferSubAccountToMaster" are attaching parameters in the body.
Do you think the issue might be caused by Escape Characters like "@" changed to "%40" in the body? I could imagine that without proper header, binance might think the email is malformed. Can you try to debug with quering the email and other params in the URI?

**Comment by milannovis** [comment]
changing:
return await _baseClient.SendRequestInternal<BinanceSubAccountTransaction>(_baseClient.GetUrlSpot(subAccountTransferToSubEndpoint, "sapi", "1"), HttpMethod.Post, ct, parameters, true).ConfigureAwait(false);
to:
return await _baseClient.SendRequestInternal<BinanceSubAccountTransaction>(_baseClient.GetUrlSpot(subAccountTransferToSubEndpoint, "sapi", "1"), HttpMethod.Post, ct, parameters, true, **true, PostParameters.InUri**).ConfigureAwait(false);

solved the issue

**Comment by JKorf** [comment]
I've adjusted the call as suggested by @milannovis , let me know if it works for you

**Comment by JKorf** [comment]
Assuming this works now
