### ISSUE TITLE
Market Buy/Sell - orderResult return 0 Price?

### ISSUE THREAD

**Issue by kingchenc** [JKorf/Binance.Net#69]
Hello,

The orderResult after a Market Buy/Sell isnt correcntly working or i make a mistake?

Starting with ->

`var orderResult = await client.PlaceOrderAsync(z3, Binance.Net.Objects.OrderSide.Buy, Binance.Net.Objects.OrderType.Market, investcalc2);`

Marked Buy is working, but its return 0 Price? Why?
Same here, after checking the order, price is 0..? ---->

`
var queryOrder = await client.QueryOrderAsync(z3, Convert.ToInt32(orderResult.Data.OrderId));`

thx for help :)

**Comment by JKorf** [comment]
Hi, 

The price isn't set for market orders. This is working as intended, because market orders don't necessarily have a single price as it can do multiple trades to fulfill the entire order. 

 If you place an order you can set the OrderResponseType in the request. If you put this on Full, the request will return the trades that were executed in the Fills field. If you want to retrieve the price later on you'll have to use the GetMyTrades function.
