### ISSUE TITLE
OrderBook in real-time not possible

### ISSUE THREAD

**Issue by noname9312** [JKorf/Binance.Net#696]
Im trying to subscribe the order book in real-time. Unfortunatly im facing issues with it. Could you please support?

`socketClient.Spot.SubscribeToOrderBookUpdates(coin, 0, data => OrderBookMessageHandler(data));`
Runtime error: ArgumentException: 0 not allowed for parameter updateInterval, allowed values: 100, 1000 
![orderbook error](https://user-images.githubusercontent.com/44933456/115759959-21f99900-a3a1-11eb-83ef-9d7ff40c2424.png)

`socketClient.Spot.SubscribeToOrderBookUpdates(coin, data => OrderBookMessageHandler(data));`
Compile error: CS1501

Binance API documentation:
https://binance-docs.github.io/apidocs/spot/en/#individual-symbol-ticker-streams

Individual Symbol Book Ticker Streams
Pushes any update to the best bid or ask's price or quantity in real-time for a specified symbol.
Stream Name: <symbol>@bookTicker
Update Speed: Real-time

**Comment by JKorf** [comment]
The doc you linked is for the book ticker, which is the SubscribeToBookTickerUpdatesAsync method. You don't need to pass the updateInterval there since it is realtime as you mentioned. 

To receive an up to date order book you can use SubscribeToPartialOrderBookUpdates. This is however limited to an update every 100 or 1000ms for spot.

**Comment by noname9312** [comment]
my bad then. thank you
