### ISSUE TITLE
client.FuturesCoin.GetPositionAdlQuantileEstimation error.

### ISSUE THREAD

**Issue by arcadeindy** [JKorf/Binance.Net#726]
var mADLInfo = client.FuturesCoin.GetPositionAdlQuantileEstimation(a.Symbol);
if (mADLInfo != null)
{
    if (mADLInfo.Success)
    {
        foreach (var c in mADLInfo.Data)
        {
            Console.WriteLine("Asset ADL             : " + c.AdlQuantile);

        }
    }
    else
    {
        Console.WriteLine("Asset ADL             : " + mADLInfo.Error.ToString());
    }
}
Console.WriteLine("==============================================");

I get result from console >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Asset Name            : XRPUSD_PERP
Asset PositionSide    : Both
Asset PositionAmount  : -797
Asset Leverage        : 1
Asset ADL             : : [5] Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Binance.Net.Objects.Futures.FuturesData.BinanceFuturesQuantileEstimation]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'symbol', line 1, position 10. {
  "symbol": "XRPUSD_PERP",
  "adlQuantile": {
    "LONG": 0,
    "SHORT": 0,
    "BOTH": 2
  }
}

**Comment by prandini** [comment]
I have got same problem here,

when call:
binanceClient.UsdFuturesApi.Account.GetPositionAdlQuantileEstimationAsync(Symbol);

Error.Message:
Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Binance.Net.Objects.Models.Futures.BinanceFuturesQuantileEstimation]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'symbol', line 1, position 10.


btw, calling from postman works fine.

anyone could help with that?
