### ISSUE TITLE
BinanceSpotSymbolOrderBook

### ISSUE THREAD

**Issue by ZigmundL** [JKorf/Binance.Net#732]
Hello. There's BinanceSpotSymbolOrderBook that automatically sync orderbook and manages connection. So if I want to subscribe to any other thing, I'll have to create another connection. Is it possible to merge them somehow, so that there would be a single ws connection?

**Comment by HypsyNZ** [comment]
![](https://i.imgur.com/ydM8uQD.png)

```cs
private readonly BinanceSocketClient _socketClient;
```

I  don't know, Can you?

**Comment by JKorf** [comment]
Currently every subscribe call in the library uses a single websocket connection. This is due to this package existing before the subscribe/unsubscribe functionality existed on the Binance API. So at the moment what you're asking is not possible no. My intention is to refactor at some point so websocket connections can be used for multiple subscriptions, but there is no ETA for that. 

That being said, is there a specific reason you would want to have a single websocket connection?

**Comment by ZigmundL** [comment]
Nothing specific, single ws connection feels right for me, I suppose that binance might not like multiple ws connections. I know that some cryptoexchanges have this as a rule, like "You can have N ws connections per IP".

**Comment by HypsyNZ** [comment]
> Nothing specific, single ws connection feels right for me, I suppose that binance might not like multiple ws connections. I know that some cryptoexchanges have this as a rule, like "You can have N ws connections per IP".

```
Websocket Limits
WebSocket connections have a limit of 5 incoming messages per second. A message is considered:
A PING frame
A PONG frame
A JSON controlled message (e.g. subscribe, unsubscribe)
A connection that goes beyond the limit will be disconnected; IPs that are repeatedly disconnected may be banned.
**A single connection can listen to a maximum of 1024 streams.**
```

https://binance-docs.github.io/apidocs/spot/en/#limits

**Comment by JKorf** [comment]
In the latest beta version it is now possible to pass in a socketClient into the options for the BinanceSpotSymbolOrderBook. When doing so it will re-use the connections available in that socket client instance, up to a max of 10 subscription per websocket connection ( this is configurable with the `SocketSubscriptionsCombineTarget` option for the socket client)
