### ISSUE TITLE
BinanceOrderBookOptions Limit cannot be set to above 20

### ISSUE THREAD

**Issue by jozamm** [JKorf/Binance.Net#857]
Dear all,

I am using the BinanceSpotSymbolOrderBook with the limit and updateInterval parameter. These parameters are sent via the BinanceOrderBookOptions class. When the limit is set to greater than 20 the method never connects and the order book is not updated. Also an exception is thrown when the Resut.Sucess is queried. However when the limit parameter is left open than it operates correctly and the whole order book is downloaded but the system is slow as the order book is quite large.

However there is a problem with the Ask list. With the limit set to 20 the ask list is showing me the from the 21st to the 40th position not from the 1st to the 20th position. An image has been attached. It is present in other tickers as well. There are no problems with the bid list.

Any help would be appreciated,

Regards,

Joseph

![Error](https://user-images.githubusercontent.com/3351232/132255246-1aecdbe6-18e4-4f78-81e8-3f24284895eb.png)

**Comment by JKorf** [comment]
The limit parameter only support 5/10/20 entries. That's because the Binance API has a stream which pushes the full 5, 10 or 20 entry order book. If the limit parameter in the BinanceSpotSymbolOrderBook is set it will use that stream, else it uses the full orderbook stream. 

I can't reproduce the issue with skipping the first 20 asks. If you can reproduce it, could you maybe create a minimal example for it?
